name: Release for Mod
on:
  workflow_dispatch:
  release:
    branches:
      - main
    paths:
      - gradle/**
      - src/**
      - build.gradle
      - gradle.properties
      - settings.gradle

jobs:
  build:
    uses: ./.github/workflows/build_and_test.yml
    with:
      ci_build: false
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - build
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
